version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app-dev
    working_dir: /app
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

